version: '3'
services:
  challenge:
    build: ./server
    ports:
      - "10011:8080"
    links:
      - redis
    environment:
      - UWSGI_INI=/home/ctf/uwsgi.ini
      - LISTEN_PORT=8080
    restart: always

  redis:
    build: ./redis
    restart: always
